### ISSUE TITLE
Abstract Review Process

### ISSUE THREAD

**Issue by moorepants** [mechmotum/bmd2023#14]
# Abstract Pre-review

Each abstract submitted should be checked as soon as possible for three things:

1. Whether the submission and abstract template instructions followed. Examples include: more that two pages, edited parts fo the template that shouldn't have been edited, not following APA citation style, did not upload an ODT, DOCX, or zip with latex files.
2. Whether the correct metadata was supplied to the Orvium form.
3. Whether the submission is spam or inappropriate.
4. Whether the HTML and PDF versions of the abstracts are properly generated.

If there are issues in 1 or 2, the editorial assistants should contact the submitting author using the Orvium response template and let them know what they need to correct. For abstracts submitted in the last few days of February, we can give them until March 3rd to correct their submissions, otherwise they should correct it by the February 28th due date.

For spam or inappropriate content, we should reject it outright and the editorial assistants should inform the author with the Orvium response template.

For issues in 4, the editorial assistants should let the Orvium developers know about the issues at support@orvium.io.

Content should not be checked at this stage, but if the editorial assistants notice some formatting errors or such in the content they can mention this to the authors as a courtesy.

Once the author(s) have corrected items 1 and 2 (and ideally 4 is fixed), we can make the abstract public and mark it as preprint version 1.

# Abstract reviews

We assign two reviewers from the scientific committee to each abstract. Each reviewer will have multiple reviews to do (up to 5). We will assign that reviewer to the abstract in Orvium. The reviewers will rate and comment on each abstract:

- Give a numerical rating (1-5) and a single sentence comment for these three qualities:
  - Fits the topic and theme of the conference
  - Scientific soundness
  - Communication of the content
- Recommend: Accept (oral), accept (poster), or reject
  - If a reject, provide the reason.
  -  If accepted (optionally) feedback on what to fix/adjust in the abstract to make it ready for publishing

Reviewers should not include their name or identifiable information in the submitted review text.

Editorial assistants review the reviews and make sure there are no inappropriate comments from the reviewers. They should check with the editors if they find anything questionable.

- The organizing committee decides on the number of oral presentation and number of poster presentations we can have.
- The organizing committee and editorial assistants tally the ratings and comments.
- We develop a ranking algorithm for the numerical ratings.
- We rank the submissions and decide on acceptances and rejections based on rankings and comments.

We release the acceptance/rejection results via Orvium to the authors and publish the reviews alongside the abstracts.

# Abstract final versions

Accepted authors may submit updated abstracts with minor adjustments for the published version. Editorial assistants review the abstracts to make sure there are no drastic changes that would alter the review decisions. Then we publish the final abstract versions.

# Paper pre-review

Similar to the abstracts, editorial assistants review for steps 1-4 above. If good, we published the preprint to Orvium for conference attendees (and the public) to see.

# Paper reviews

TBD

**Comment by chris-konrad** [comment]
Looks good to me! You have a couple of typos here and there:

> Examples include: more that two pages,

> Editorial assistants review the reviews and make sure there are no inappropriate comments from the reviewers.

**Comment by chris-konrad** [comment]
Here, you probably mean 4 instead of 3 

>Once the author(s) have corrected items 1 and 2 (and ideally 3 is fixed),

**Comment by moorepants** [comment]
What is the error in:

> Editorial assistants review the reviews and make sure there are no inappropriate comments from the reviewers.

I'm not seeing it :(

**Comment by chris-konrad** [comment]
Me neither. Can't remember what bothered me yesterday ...

**Comment by moorepants** [comment]
Ok, I've sent it to the library and orvium people for comment. Will present on the 10th to the organizing committee.

**Comment by moorepants** [comment]
Here is my current revision after taking feedback from Orvium, Library, and Organizing Committee:

# Abstract Pre-review

Each abstract submitted should be checked as soon as possible for three things:

1. Whether the submission is spam or inappropriate.
2. Whether the submission and abstract template instructions were followed.
   Examples include: more that two pages, edited parts fo the template that
   shouldn't have been edited, not following APA citation style, did not upload
   an ODT, DOCX, or zip with latex files.
3. Whether the correct metadata was supplied to the Orvium form.
4. Whether the HTML and PDF versions of the abstracts are properly generated.

The editorial assistants should assign themselves as an editor to the
submission, so we all know who is handling the pre-review.

For spam or inappropriate content (1.), we should reject it outright and the
editorial assistants should inform the author by pressing "Reject" button in
Orvium. Use template text for this response and state the reason clearly. If
you'd like someone on the organizing committee to handle this, let them know.

If there are issues in (2.) or (3.), the editorial assistants should contact
the submitting author using the Orvium "Request Changes" button and use the
template text for this step to let them know what they need to correct.

For abstracts submitted in the last few days of February, we can give them
until March 3rd to correct their submissions, otherwise they should correct it
by the orginal February 28th due date.

For issues in 4, the editorial assistants should let the Orvium developers know
about the issues at support@orvium.io.

Article content should not be checked at this stage, but if the editorial
assistants notice some formatting errors or such in the content they can
mention this to the authors as a courtesy.

Authors should then edit their submission by pressing "Edit" and submitting a
new document and/or correcting the metadata.

TODO : Ask Orvium why the article does not display as Version 2 if the author
edits the submission.

Once the author(s) have corrected items 2 and 3 (and ideally 4 is fixed), the
"Assign Editor" should be set to "Jason Moore" to signal that this is ready to
have reviewers assigned.

Do not "Accept" the abstracts at this point, as it will make the abstract
public. We will make the accepted abstracts and their reviews public after
we've made the final selection of presentation, poster, or rejection.

# Abstract reviews

We will assign two reviewers from the scientific committee to each abstract by
pressing "Invite Reviewers" on the abstract submission in Orvium. Each reviewer
will review up to 5 abstracts.

The reviewer must have an account on Orvium to be invited. If they are invited
they will receive an email inviting them. The click on the email link which
brings them to the abstract in Orvium. Then they select "My Reviews" on the
left and there is a blue "Accept the Invitation" button. Once they accept they
can submit a review.

The reviewers will rate and comment on each abstract:

- Provide a comment for these three qualities:
  - Fits the topic and theme of the conference
  - Scientific and technical soundness
  - Communication of the content
- Recommend: Accept (oral), accept (poster), or reject
  - If a reject, provide the reason.
  - If accepted (optionally) feedback on what to fix/adjust in the abstract to
    make it ready for publishing in the book of abstracts (should be minor
    revisions)

In Orvium reviewers have to do three things:

1. Fill out the "general comments" box
2. Upload a document which contains the review
3. Select: "Accept", "Minor Revision", or "Major Revision"

**TODO :** The "general comments" box and uploading a document is redundant and
it would be nice if the editors did not have to open a document with the review
and could simply see it in the interface.

We will have to tell the reviewers that the things in 3. mean:

- Accept: Accept as is, no edits needed for the abstract to be published.
- Minor Revision: Accept, but abstract needs edits to be published.
- Major Revision: Reject

OR

- Accept: Oral
- Minor Revision: Poster
- Major Revision: Reject

or the Orvium drop down is changed to say: oral, poster, reject

Reviewers should not include their name or identifiable information in the
submitted review text. We need to check each review to make sure identifiable
info is not present.

The reviewer selects "Submit" to deliver the review to the editor.

**TODO :** It seems pressing "Submit" allows the author to immediately see the
review. We'd like to moderate the reviews in case someone says inappropriate
comments.

Editorial assistants review the reviews and make sure there are no
inappropriate comments from the reviewers. They should check with the editors
if they find anything questionable.

- The organizing committee decides on the number of oral presentation and
  number of poster presentations we can have.
- The organizing committee and editorial assistants tally the ratings and
  comments.
- We develop a ranking algorithm for the numerical ratings.
- We rank the submissions and decide on acceptances and rejections based on
  rankings and comments.
- We select "Poster", "Presentation", or "None" in the "Decision" drop down
  beside each abstract in the moderator panel.
- We press "Accept" for all accepted reviews and "Reject" for all rejected
  reviews in teh moderator panel.

**TODO :** Selecting the "Decision" drop down does not seem to signal to the
author whether their paper has been accepted or rejected.

# Reviewer Instructions

1. Create an account on Orvium
2. Check your email for review invitations.
3. Log into Orvium
4. Accept the review invitations under "My Reviews" on the left side of the
   Orvium website after logging in.
5. Type your recommendation: Accept Oral, Accept Poster, Reject into the
   "General Comments" field.
6. Upload a file with your review text.
7. Select "Accept", "Minor Revision=Edit Abstract", or "Major Revision=Reject"
8. Submit the review.
9. Repeat for each of your reviews.

The text of your should briefly comment on these three qualities:

- Whether the submission fits the topic and theme of the conference
- Whether the work is scientifically and technically sound
- Whether the content is communicated well

You should make one of three recommendations:

- Accept for an oral presentation
- Accept for a poster presentation
- Reject

If you recommend to reject, provide a reason for your recommendation.

If you recommend to accept, optionally provide feedback feedback on what to
fix/adjust in the abstract to make it ready for publishing in the book of
abstracts. These should be minor revision requests and are only intended to
improve the abstract communication for the published book of abstracts.

# Abstract final versions

Accepted authors may submit updated abstracts with minor adjustments for the
published version. Editorial assistants review the abstracts to make sure there
are no drastic changes that would alter the review decisions. Then we publish
the final abstract versions.

# Paper pre-review

Similar to the abstracts, editorial assistants review for steps 1-4 above. If
good, we published the preprint to Orvium for conference attendees (and the
public) to see.

# Paper reviews

TBD
