### ISSUE TITLE
Abstract Pre-Review Text Template

### ISSUE THREAD

**Issue by chris-konrad** [mechmotum/bmd2023#15]
I suggest we decide on standardized word choice for pre-review change requests and rejections due to spam.. Here is a proposal by Animesh and me:

**For requesting editorial changes:**
"We have found some formal issues in the abstract which need to be corrected before the abstract can be considered by our reviewers. Please make the following changes by March 3rd: (1) _Do this._ (2) _Do that._ ... (n) _Do yet another thing._ [Editorial hint for courtesy, optional] Additionally we recommend you to _change some formatting errors_, to improve the chances of being accepted by the reviewers. [Editorial hint over] You can change your submission by accessing it in Orvium, clicking "edit", and then uploading a revised version. "

Unfortunately, the autogenerated email only allows for continuous text, we can't make a bullet-point list. This is how it will look like:

![image](https://user-images.githubusercontent.com/115986935/216118485-75704b79-5371-4d5a-923b-fb750af920ff.png)

**For rejecting spam:**
"The uploaded document was classified spam or otherwise inappropriate. If you wish to contribute to BMD2023, please review your submission. "

What do you think?

**Comment by moorepants** [comment]
- Only use March 3rd for those that submit in the last few days of the open period. Say Feb 28 for those that submit earlier.
- Change to "The uploaded document was classified spam or otherwise inappropriate and has been rejected. If you wish to contribute to BMD2023, please make a new appropriate submission."

**Comment by chris-konrad** [comment]
Noted!
