### ISSUE TITLE
Disclaimer about permitted file formats in the instructions. 

### ISSUE THREAD

**Issue by chris-konrad** [mechmotum/bmd2023#16]
While doing some testing today I realized that Orvium still shows a red warning while uploading anything else then .docx. We should add a disclaimer that this warning can be ignored in case of .odt and .zip to our instructions on this website. Otherwise people might get confused or feel insecure about using .odt or latex. 

That's how it looks in Orvium: 
![image](https://user-images.githubusercontent.com/115986935/216127189-efc3cc72-a800-4489-a35d-f48aa4e90240.png)

**Comment by moorepants** [comment]
Can you report that to the Orvium devs? That seems problematic even if we have the disclaimer here on this site.

**Comment by moorepants** [comment]
Actually I just saw that there are new buttons in the settings for odt and zip:
![image](https://user-images.githubusercontent.com/276007/216358442-0a8997ea-32bb-4db8-ab97-925b42e4788d.png)

I've now enabled them.
